---
apiVersion: v1
kind: Secret
metadata:
  name: private-repo
  namespace: argo-cd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: git@github.com:mohankala/argo-cd-private.git
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
    QyNTUxOQAAACAsNguQYt5dBLPRQj5VuNSXGCyZ393js7kfP8DY9IIqNgAAAKCYmObTmJjm
    0wAAAAtzc2gtZWQyNTUxOQAAACAsNguQYt5dBLPRQj5VuNSXGCyZ393js7kfP8DY9IIqNg
    AAAEB8d0+0qtHYiklLBHVGVOl4z/LPQump1fZtl1zQjNiuSiw2C5Bi3l0Es9FCPlW41JcY
    LJnf3eOzuR8/wNj0gio2AAAAFmthbGFtb2hhbnJhb0BnbWFpbC5jb20BAgMEBQYH
    -----END OPENSSH PRIVATE KEY-----
  insecure: "false"
  enableLfs: "true"